version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # This name must match what is used in 'bin.install' below
    binary: surge 

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:
  - formats: [ tar.gz ]
    # use zip for windows
    format_overrides:
      - goos: windows
        formats: [ zip ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: surge
    repository:
      owner: surge-downloader
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/surge-downloader/surge"
    description: "Surge is an open-source download manager"
    license: "MIT"
    directory: Formula 
    
    # 3. Install Script
    install: |
      bin.install "surge"
    test: |
      system "#{bin}/surge", "--version"
